# coding: utf-8

"""
    SendX REST API

    # Introduction The SendX API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs. The SendX Rest API doesn’t support bulk updates. You can work on only one object per request. <br> 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sendx_python_sdk.models.report_data import ReportData

class TestReportData(unittest.TestCase):
    """ReportData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportData:
        """Test ReportData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportData`
        """
        model = ReportData()
        if include_optional:
            return ReportData(
                campaign_id = 'sendx123',
                link_stats = {"www.example.com":123},
                clicked_contact_count = 230,
                opened_contact_count = 345,
                replied_contact_count = 12,
                clicked_unique_contact_count = 210,
                opened_unique_contact_count = 320,
                replied_unique_contact_count = 11,
                sent_contact_count = 500,
                unsubscribe_contact_count = 10,
                bounce_contact_count = 5,
                spam_contact_count = 2,
                email_revenue = '$5000',
                revenue_per_recipient = '$10',
                currency = 'USD'
            )
        else:
            return ReportData(
        )
        """

    def testReportData(self):
        """Test ReportData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
